spring.application.name: product-composite-service
server.port: 7001

app:
  product-service:
    host: localhost
    port: 7002
  review-service:
    host: localhost
    port: 7004
  recommendation-service:
    host: localhost
    port: 7003

---

spring.config.activate.on-profile: docker
server.port: 9666

app:
  product-service:
    host: product-service
    port: 9666
  review-service:
    host: review-service
    port: 9666
  recommendation-service:
    host: recommendation-service
    port: 9666
