spring:
  application:
    name: recommendation-service
  mongodb:
    uri: mongodb://localhost:27018/recommendation-db
server:
  port: 7003

---

spring:
  config:
    activate:
      on-profile: docker
  mongodb:
    uri: mongodb://mongodb:27017/recommendation-db
server:
  port: 9666
