spring:
  application:
    name: product-service
  mongodb:
    uri: mongodb://localhost:27017/product-db
server:
  port: 7002

---
spring:
  config:
    activate:
      on-profile: docker
  mongodb:
    uri: mongodb://mongodb:27017/product-db
server:
  port: 9666

